print('Faça sua soma aqui')
valor_1 = int(input('digite o primeiro valor: '))
valor_2 = int(input('digite o segundo valor: '))
soma = int(valor_1 + valor_2)
print('Este é o valor de sua soma: {} + {} = {}' .format(valor_1, valor_2, soma))